log:
  level: info
dns:
  servers:
    - tag: dns-remote
      type: tls
      server: dns11.quad9.net
      domain_resolver: dns-direct
      detour: proxy
    - tag: dns-direct
      type: tls
      server: dot.pub
      domain_resolver: dns-local
    - tag: dns-local
      type: tcp
      server: 101.226.4.6
  rules:
    - action: reject
      rule_set: geosite-category-ads-all
    - server: dns-remote
      clash_mode: global
    - server: dns-direct
      clash_mode: direct
    - server: dns-direct
      rule_set: geosite-cn
  final: dns-remote
inbounds:
  - tag: tun-in
    type: tun
    address:
      - 172.18.0.1/30
      - fdfe:dcba:9876::1/126
    mtu: 9000
    auto_route: true
    strict_route: true
    stack: gvisor
outbounds:
  - tag: direct
    type: direct
    domain_resolver: dns-direct
  - tag: proxy
    type: selector
    outbounds:
      - auto
      - _PROXY_TAGS_
    default: auto
  - tag: auto
    type: urltest
    outbounds:
      - _PROXY_TAGS_
  - _PROXY_NODES_
route:
  rules:
    - action: sniff
    - action: hijack-dns
      protocol: dns
    - outbound: direct
      ip_is_private: true
    - action: reject
      rule_set: geosite-category-ads-all
    - outbound: proxy
      clash_mode: global
    - outbound: direct
      clash_mode: direct
    - outbound: direct
      rule_set: geosite-cn
    - outbound: direct
      rule_set: geoip-cn
  rule_set:
    - _REMOTE_RULESETS_
  final: proxy
  auto_detect_interface: true
  default_domain_resolver: dns-direct
experimental:
  cache_file:
    enabled: true
