log:
  disabled: false
  level: info
dns:
  servers:
    - tag: dns-remote
      type: tls
      server: 149.112.112.10
      detour: proxy
    - tag: dns-direct
      type: tls
      server: 223.5.5.5
  rules:
    - action: reject
      rule_set:
        - geosite-category-ads-all
    - server: dns-remote
      rule_set:
        geosite-geolocation-!cn
      strategy: prefer_ipv6
    - server: dns-direct
      rule_set:
        - geosite-cn
      strategy: ipv4_only
  final: dns-remote
  strategy: ipv4_only
inbounds:
  - tag: tun-in
    type: tun
    address:
      - 172.18.0.1/30
      - fdfe:dcba:9876::1/126
    route_exclude_address:
      - 192.168.0.0/16
      - fc00::/7
    loopback_address:
      - 10.7.0.1
    mtu: 9000
    auto_route: true
    strict_route: true
    stack: gvisor
outbounds:
  - tag: direct
    type: direct
  - tag: proxy
    type: selector
    outbounds:
      - auto
      - _PROXY_TAGS_
    default: auto
  - tag: auto
    type: urltest
    outbounds:
      - _PROXY_TAGS_
  - _PROXY_NODES_
route:
  rules:
    - action: sniff
    - action: hijack-dns
      protocol: dns
    - outbound: direct
      ip_is_private: true
    - action: reject
      rule_set:
        - geosite-category-ads-all
    - outbound: proxy
      rule_set:
        - geosite-geolocation-!cn
    - outbound: direct
      rule_set:
        - geosite-cn
        - geoip-cn
  rule_set:
    - tag: geosite-category-ads-all
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs
    - tag: geosite-geolocation-!cn
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs
    - tag: geosite-cn
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs
    - tag: geoip-cn
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs
  final: proxy
  auto_detect_interface: true
  default_domain_resolver: dns-direct
experimental:
  cache_file:
    enabled: true