log:
  level: warn
dns:
  servers:
    - tag: dns-remote
      type: tls
      server: dns11.quad9.net
      domain_resolver: dns-local
      detour: proxy
    - tag: dns-direct
      type: tls
      server: dot.pub
      domain_resolver: dns-local
    - tag: dns-local
      type: udp
      server: 119.29.29.29
  rules:
    - action: reject
      rule_set:
        - geosite-category-ads-all
    - server: dns-remote
      rule_set:
        - geosite-geolocation-!cn
    - server: dns-direct
      rule_set:
        - geosite-cn
  final: dns-remote
inbounds:
  - tag: tun-in
    type: tun
    interface_name: neko-tun
    address:
      - 198.18.0.1/30
      - fdfe:dcba:9876::1/126
    mtu: 9000
    auto_route: true
    strict_route: true
    stack: gvisor
outbounds:
  - tag: direct
    type: direct
    domain_resolver: dns-direct
  - tag: proxy
    type: selector
    outbounds:
      - auto
      - _PROXY_TAGS_
      - direct
    default: auto
  - tag: auto
    type: urltest
    outbounds:
      - _PROXY_TAGS_
  - _PROXY_NODES_
route:
  rules:
    - action: sniff
    - outbound: direct
      ip_is_private: true
    - action: hijack-dns
      protocol: dns
    - action: reject
      rule_set:
        - geosite-category-ads-all
    - outbound: proxy
      rule_set:
        - geosite-geolocation-!cn
    - outbound: direct
      rule_set:
        - geosite-cn
        - geoip-cn
  rule_set:
    - tag: geosite-category-ads-all
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs
    - tag: geosite-geolocation-!cn
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs
    - tag: geosite-cn
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs
    - tag: geoip-cn
      type: remote
      format: binary
      url: https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs
  final: proxy
  auto_detect_interface: true
  default_domain_resolver: dns-direct
experimental:
  cache_file:
    enabled: true
